src/QualityBags/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace QualityBags.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/QualityBags/Controllers/OrderBagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QualityBags.Data;
using QualityBags.Models;
using Microsoft.AspNetCore.Authorization;

namespace QualityBags.Controllers
{
    [AllowAnonymous]
    [Authorize(Roles = "Admin, Member")]
    public class OrderBagsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderBagsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OrderBags
        public async Task<IActionResult> Index(string SearchString, string currentFilter, int? id, int? page)
        {
            ViewBag.Categories = _context.Categories.ToList();

            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }

            ViewData["CurrentFilter"] = SearchString;
            var bags = from b in _context.Bags.Include(b => b.Category)
                       select b;

            if (id != null)
            {
                bags = bags.Where(b => b.CategoryID == id);
            }

            if (!String.IsNullOrEmpty(SearchString))
            {
                bags = bags.Where(b => b.Name.Contains(SearchString));
            }

            int pageSize = 8;
            return View(await PaginatedList<Bag>.CreateAsync(bags.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: OrderBags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bag = await _context.Bags.SingleOrDefaultAsync(m => m.BagID == id);
            if (bag == null)
            {
                return NotFound();
            }

            return View(bag);
        }


        // GET: OrderBags/Create
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name");
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "EmailAddress");
            return View();
        }

        // POST: OrderBags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BagID,CategoryID,Description,Name,PathOfFile,Price,SupplierID")] Bag bag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bag);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name", bag.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "EmailAddress", bag.SupplierID);
            return View(bag);
        }

        // GET: OrderBags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bag = await _context.Bags.SingleOrDefaultAsync(m => m.BagID == id);
            if (bag == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name", bag.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "EmailAddress", bag.SupplierID);
            return View(bag);
        }

        // POST: OrderBags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BagID,CategoryID,Description,Name,PathOfFile,Price,SupplierID")] Bag bag)
        {
            if (id != bag.BagID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BagExists(bag.BagID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name", bag.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "EmailAddress", bag.SupplierID);
            return View(bag);
        }

        // GET: OrderBags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bag = await _context.Bags.SingleOrDefaultAsync(m => m.BagID == id);
            if (bag == null)
            {
                return NotFound();
            }

            return View(bag);
        }

        // POST: OrderBags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bag = await _context.Bags.SingleOrDefaultAsync(m => m.BagID == id);
            _context.Bags.Remove(bag);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool BagExists(int id)
        {
            return _context.Bags.Any(e => e.BagID == id);
        }

    }
}

src/QualityBags/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About us";
}

<div class="col-md-5">
    <div class="about">
        <h3>OUR STORY</h3>
        <p>Started in 1941 as a family-run workshop in Auckland City, we were pioneers in the leather goods and accessories space, establishing ourselves as the original American house of leather during the second half of the 20th Century.</p>
        <p>We went on to define “accessible luxury” for a generation. Beginning in New Zealand, Quality Bags delivered an alternative to traditional luxury. </p>
        
        <p>Now, we’re building on our brand strengths with a vision:</p>
        <h2>“To become the company that defines global modern luxury.”</h2>
        <p>At Quality Bags, we believe an inspirational and modern work environment is where exceptional talent thrives.</p>
        <p>
            We nurture a culture infused with creativity, innovation, entrepreneurship, learning and achievement to allow our people to always bring their best.
            We are inspired, talented, and diverse individuals who work collaboratively to drive the continued success of our brand.
        </p>
        <p>And, we know the culture is truly a reflection of our people—both who we are and who we strive to be, simply defined by our Values.</p>
    </div>
</div>
<div class="col-md-7">
    <img class="img-responsive" src="~/images/ourhistory.jpg" alt="history" />
</div>






src/QualityBags/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}


<h2 class="put_center">@ViewData["Title"]</h2>

<div class="contact">
    <img src="~/images/ContactBg.jpg" alt="" class="img-responsive"/>
    
    <h2>
        <strong>Address:</strong><br />
        Building 183<br /> 139 Carrington Road<br />Mt Albert, Auckland<br /> New Zealand

        <br />
        <br />
        <strong>Phone:</strong><br />
        (09)-123 4567
        <br />
        <br />
        <strong>Email:</strong><br />
        support@quanlitybags.co.nz
    </h2>

</div>




src/QualityBags/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<environment names="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</environment>

<div class="container">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="~/images/banner_01.jpg" alt="ASP.NET" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        Enjoy our bags<br />
                        <a class="btn btn-default" asp-controller="OrderBags" asp-action="Index">SHOP NOW</a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/banner_02.jpg" alt="Visual Studio" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        Enjoy our bags<br />
                        <a class="btn btn-default" asp-controller="OrderBags" asp-action="Index">SHOP NOW</a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/banner_03.jpg" alt="Package Management" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        Enjoy our bags<br />
                        <a class="btn btn-default" asp-controller="OrderBags" asp-action="Index">SHOP NOW</a>
                    </p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<br />
<div class="container">
    <!--Featured Item-->
    <div class="spec">
        <h3>Featured Items</h3>
        <div class="ser-t">
            <b></b>
            <span><i></i></span>
            <b class="line"></b>
        </div>
    </div> <!-- //Featured Item-->

    <div class="row">
        <div class="col-md-3 put_center">
            <img class="maxwidth" src="~/images/crossbody.jpg" alt="crossbody bag" />
            <a class="btn btn-default" asp-action="Index" asp-controller="OrderBags" asp-route-id="1">More Handbags</a>
        </div>
        <div class="col-md-3 put_center">
            <img class="maxwidth" src="~/images/backpack.jpg" alt="backpack bag" />
            <a class="btn btn-default" asp-action="Index" asp-controller="OrderBags" asp-route-id="2">More Backpacks</a>
        </div>
        <div class="col-md-3 put_center">
            <img class="maxwidth" src="~/images/tote.jpg" alt="tote bag" />
            <a class="btn btn-default" asp-action="Index" asp-controller="OrderBags" asp-route-id="3">More Totes</a>
        </div>
        <div class="col-md-3 put_center">
            <img class="maxwidth" src="~/images/satchel.jpg" alt="satchel bag" />
            <a class="btn btn-default" asp-action="Index" asp-controller="OrderBags" asp-route-id="4">More Satchels</a>
        </div>
    </div>

</div>