src/QualityBags/Controllers/BagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QualityBags.Data;
using QualityBags.Models;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace QualityBags.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BagsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnv;

        public BagsController(ApplicationDbContext context, IHostingEnvironment hostingEnv)
        {
            _context = context;
            _hostingEnv = hostingEnv;
        }

        // GET: Bags
        public async Task<IActionResult> Index()
        {
            var bags = _context.Bags.Include(b => b.Category).Include(b => b.Supplier).AsNoTracking();
            return View(await bags.ToListAsync());
        }

        // GET: Bags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bag = await _context.Bags.SingleOrDefaultAsync(m => m.BagID == id);
            if (bag == null)
            {
                return NotFound();
            }

            return View(bag);
        }

        // GET: Bags/Create
        public IActionResult Create()
        {
            PopulateCategoryDropDownList();
            PopulateSupplierDropDownList();
            return View();
        }

        // POST: Bags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryID,Description,Name,Price,SupplierID")] Bag bag, IFormFile uploadFile)
        {
            var relativeName = "";
            var fileName = "";

            if (uploadFile != null && uploadFile.Length > 0)
            {
                fileName = ContentDispositionHeaderValue.Parse(uploadFile.ContentDisposition).FileName.Trim('"');
                //Path for localhost
                relativeName = "/Images/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;
                using (FileStream fs = System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
                {
                    await uploadFile.CopyToAsync(fs);
                    fs.Flush();
                }
            }
            else
            {
                relativeName = "/Images/bag1.jpg";
            }
            bag.PathOfFile = relativeName;
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(bag);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                PopulateCategoryDropDownList(bag.CategoryID);
                PopulateSupplierDropDownList(bag.SupplierID);

            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }

            return View(bag);
        }

        // GET: Bags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bag = await _context.Bags.SingleOrDefaultAsync(m => m.BagID == id);
            if (bag == null)
            {
                return NotFound();
            }
            PopulateCategoryDropDownList(bag.CategoryID);
            PopulateSupplierDropDownList(bag.SupplierID);
            return View(bag);
        }

        // POST: Bags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BagID,PathOfFile,CategoryID,Description,Name,Price,SupplierID")] Bag bag, IFormFile uploadFile)
        {
            var relativeName = "";
            var fileName = "";

            if (uploadFile != null && uploadFile.Length > 0)
            {
                fileName = ContentDispositionHeaderValue.Parse(uploadFile.ContentDisposition).FileName.Trim('"');
                //Path for localhost
                relativeName = "/Images/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;
                using (FileStream fs = System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
                {
                    await uploadFile.CopyToAsync(fs);
                    fs.Flush();
                }
            }
            else
            {
                relativeName = bag.PathOfFile;
            }
            bag.PathOfFile = relativeName;

            if (id != bag.BagID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BagExists(bag.BagID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            PopulateCategoryDropDownList(bag.CategoryID);
            PopulateSupplierDropDownList(bag.SupplierID);
            return View(bag);
        }



        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int? id, IFormFile uploadFile)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var relativeName = "";
        //    var fileName = "";
        //    var editbag = await _context.Bags.SingleOrDefaultAsync(b => b.BagID == id);

        //    if (uploadFile != null && uploadFile.Length > 0)
        //    {
        //        fileName = ContentDispositionHeaderValue.Parse(uploadFile.ContentDisposition).FileName.Trim('"');
        //        //Path for localhost
        //        relativeName = "/Images/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;
        //        using (FileStream fs = System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
        //        {
        //            await uploadFile.CopyToAsync(fs);
        //            fs.Flush();
        //        }
        //    }
        //    else
        //    {
        //        relativeName = "/Images/bag1.jpg";
        //    }


        //    editbag.PathOfFile = relativeName;

        //    if (await TryUpdateModelAsync<Bag>(editbag, "", 
        //        b => b.Name, b => b.Description, b => b.CategoryID, b => b.SupplierID, b => b.Price))
        //    {
        //        try
        //        {
        //            await _context.SaveChangesAsync();
        //            return RedirectToAction("Index");
        //        }
        //        catch (DbUpdateException /* ex */)
        //       {
        //            //Log the error (uncomment ex variable name and write a log.)
        //            ModelState.AddModelError("", "Unable to save changes. " +
        //                "Try again, and if the problem persists, " +
        //                "see your system administrator.");
        //        }
        //    }

        //    PopulateCategoryDropDownList(editbag.CategoryID);
        //    PopulateSupplierDropDownList(editbag.SupplierID);
        //    return View(editbag);
        //}


        //public async Task<IActionResult> Edit(int? id, IFormFile file)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var relativeName = "";
        //    var fileName = "";
        //    var editbag = await _context.Bags.SingleOrDefaultAsync(b => b.BagID == id);

        //    if (file != null && file.Length > 0)
        //    {
        //        fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
        //        //Path for localhost
        //        relativeName = "/Images/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;
        //        using (FileStream fs = System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
        //        {
        //            await file.CopyToAsync(fs);
        //            fs.Flush();
        //        }
        //    }
        //    else
        //    {
        //        relativeName = "/Images/bag1.jpg";
        //    }


        //    editbag.PathOfFile = relativeName;

        //    if (await TryUpdateModelAsync<Bag>(editbag, "",
        //        b => b.Name, b => b.Description, b => b.CategoryID, b => b.SupplierID, b => b.Price, b => b.PathOfFile))
        //    {
        //        try
        //        {
        //            await _context.SaveChangesAsync();

src/QualityBags/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QualityBags.Data;
using QualityBags.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Authorization;

namespace QualityBags.Controllers
{
    [Authorize(Roles = "Admin, Member")]

    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public OrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Orders
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Orders.Include(i => i.User).AsNoTracking().ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .Include(o => o.OrderItems)
                .ThenInclude(o => o.Bag)
                .ThenInclude(b => b.Category)
                .SingleOrDefaultAsync(o => o.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        [Authorize(Roles = "Admin, Member")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Member")]
        public async Task<IActionResult> CreatePost()
        {
            var order = new Order();
            ApplicationUser user = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                ShoppingCart cart = ShoppingCart.GetCart(this.HttpContext);
                List<CartItem> cartItems = cart.GetCartItems(_context);
                List<OrderItem> orderItems = new List<OrderItem>();
                foreach (CartItem ci in cartItems)
                {
                    OrderItem oi = CreateOrderDetailForThisItem(ci);
                    oi.Order = order;
                    orderItems.Add(oi);
                    _context.Add(oi);

                }

                order.User = user;
                order.Date = DateTime.Today;
                order.OrderStatus = OrderStatus.Waiting;
                order.SubTotal = ShoppingCart.GetCart(this.HttpContext).GetSubtotal(_context);
                order.GST = ShoppingCart.GetCart(this.HttpContext).GetTotalGST(_context);
                order.GrandTotal = ShoppingCart.GetCart(this.HttpContext).GetGrandTotal(_context);
                order.OrderItems = orderItems;
                _context.SaveChanges();

                return RedirectToAction("Purchased", new RouteValueDictionary(
                new { action = "Purchased", id = order.OrderID }));
            }

            return View(order);
        }

        private OrderItem CreateOrderDetailForThisItem(CartItem item)
        {

            OrderItem oi = new OrderItem();
            oi.Quantity = item.ItemCount;
            oi.Bag = item.Bag;
            oi.OrderItemPrice = item.Bag.Price;

            return oi;
        }

        public async Task<IActionResult> Purchased(int? id)
        {
            //await CreatePost();

            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .AsNoTracking()
                .SingleOrDefaultAsync(o => o.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            var orderItems = _context.OrderItems
                .Where(oi => oi.Order.OrderID == order.OrderID)
                .Include(oi => oi.Bag)
                .ThenInclude(b => b.Category)
                .ToList();

            order.OrderItems = orderItems;
            ShoppingCart.GetCart(this.HttpContext).ClearCart(_context);
            return View(order);
        }


        // GET: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .AsNoTracking()
                .SingleOrDefaultAsync(o => o.OrderID == id);

            if (order == null)
            {
                return NotFound();
            }

            var orderItems = _context.OrderItems
                .Where(oi => oi.Order.OrderID == order.OrderID)
                .Include(oi => oi.Bag)
                .ToList();

            order.OrderItems = orderItems;

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.SingleOrDefaultAsync(m => m.OrderID == id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Orders
        [Authorize(Roles = "Admin, Member")]
        //public async Task<IActionResult> CustomerIndex()
        //{
        //    return View(await _context.Orders.Include(i => i.User).AsNoTracking().ToListAsync());
        //}

        public async Task<IActionResult> CustomerIndex()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            return View(await _context.Orders.Where(o => o.User == user).Include(o => o.User).AsNoTracking().ToListAsync());
        }

        // GET: Orders/Details/5
        [Authorize(Roles = "Admin, Member")]
        public async Task<IActionResult> CustomerDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .Include(o => o.OrderItems)
                .ThenInclude(o => o.Bag)
                .ThenInclude(b => b.Category)
                .SingleOrDefaultAsync(o => o.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }
    }
}

src/QualityBags/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QualityBags</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/myStyle.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="apple-touch-icon" sizes="180x180" href="~/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" href="~/favicon/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="~/favicon/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="~/favicon/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="~/favicon/manifest.json">
        <meta name="theme-color" content="#ffffff">  
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/myStyle.css" />
        <link rel="apple-touch-icon" sizes="180x180" href="~/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" href="~/favicon/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="~/favicon/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="~/favicon/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="~/favicon/manifest.json">
        <meta name="theme-color" content="#ffffff">  
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img style="max-height:28px" src="~/images/trans_BG.png" alt="Quality Bags" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="OrderBags" asp-action="Index">Product</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Bags" asp-action="Index">Bag Management</a></li>
                                <li><a asp-area="" asp-controller="Categories" asp-action="Index">Category Management</a></li>
                                <li><a asp-area="" asp-controller="Suppliers" asp-action="Index">Supplier Management</a></li>
                                <li><a asp-area="" asp-controller="Orders" asp-action="Index">Order Management</a></li>
                                <li><a asp-area="" asp-controller="AdminApplicationUsers" asp-action="Index">Account Management</a></li>
                            </ul>
                        </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

    </div>

    <br />
    <br />
    <br />
    <br />
    <!-- footer start -->
    <footer class="footer">
        <div class="container">
            <div class="footer-left">
                <img src="~/images/orange_BG.png" width="180" alt="Quality Bags" />
                <p class="footer-links">
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    ·
                    <a asp-area="" asp-controller="OrderBags" asp-action="Index">Product</a>
                    ·
                    <a asp-area="" asp-controller="Home" asp-action="About">About</a>
                    ·
                    <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                </p>
                <p class="footer-copyright">&copy; 2017 - Quality Bags</p>
            </div>

            <div class="footer-center">

                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>Building 183, 139 Carrington Road </span>Mt Albert, Auckland, New Zealand</p>
                </div>

                <div>
                    <i class="fa fa-phone"></i>
                    <p>090000000</p>
                </div>

                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="mailto:support@wallstreetwines.co.nz">support@qualitybags.co.nz</a></p>
                </div>

            </div>

            <div class="footer-right">

                <p class="footer-designer">
                    <span>Designer</span>
                    Chong Wang <br /> SID: 1470225
                </p>
                <br>
                <div class="footer-icons">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-tumblr"></i></a>
                    <a href="#"><i class="fa fa-youtube"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
        </div>

    </footer>  <!-- footer end-->

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/imagePreview.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/imagePreview.js"></script>
    </environment>
    <script>
        $(document).ready(function () {
            $("#cart-icon").click(function(){
                $(".cart-container").slideToggle(500, function () {

                });

            })
        });
    </script>
    @RenderSection("scripts", required: false)

</body>
</html>